/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicInfoModal: typeof import('./components/Modal/BasicInfoModal.vue')['default']
    BasicTable: typeof import('./components/Table/BasicTable.vue')['default']
    DialogGroup: typeof import('./components/Modal/DialogGroup.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Greeting: typeof import('./components/Greeting.vue')['default']
    IEpSelect: typeof import('~icons/ep/select')['default']
    IEpStarFilled: typeof import('~icons/ep/star-filled')['default']
    Pagination: typeof import('./components/Table/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./components/Form/SearchForm.vue')['default']
    Spinner: typeof import('./components/Modal/Spinner.vue')['default']
    TElDatePicker: typeof import('./components/TElDatePicker.vue')['default']
    TElInput: typeof import('./components/TElInput.vue')['default']
    TElSelect: typeof import('./components/TElSelect.vue')['default']
    TestModal: typeof import('./components/Modal/TestModal.vue')['default']
    TIcon: typeof import('./components/TIcon.vue')['default']
    TSuspense: typeof import('./components/TSuspense.vue')['default']
    UserForm: typeof import('./components/Form/UserForm.vue')['default']
    UserList: typeof import('./components/Async/UserList.vue')['default']
  }
}
